### PR TITLE
Fix Gmail.check.is_inside_email()

### PR DESCRIPTION
**Pull request by josteink**
This fixes https://github.com/KartikTalwar/gmail.js/issues/620.

### CODE REVIEW

**Comment by josteink** [comment]
I've done a basic fix, and some basic-testing and it *looks right* to me, but that's about it.

But since I'm not using `gmail.check.is_inside_email()` in my production extension, so I don't have any extensive use-cases where getting it right is that important.

Could any of you guys who have expressed interest in this function in the past help test this change, and ensure we are not creating any regressions or false positives?

cc: @AlexBazer @jocstar @yevhene

**Comment by yevhene** [comment]
I can confirm, it works for me on production perfectly

**Comment by josteink** [comment]
I'll get this merged then!

**Comment by josteink** [comment]
Fix now released in version `1.0.4`.

**Pull request merged**
