### PR TITLE
Fix ajax request error.

### PR DESCRIPTION
**Pull request by Navega**
Fix ajax request: "SyntaxError: Unexpected token )", we need to specify the datatype for the response.

I am receiving a lot of errors in the console due to that problem. It isn't critical, but I recommend to fix it.

Navega, Software Developer at Appfluence Inc.

### CODE REVIEW

**Comment by josteink** [comment]
Hey there, and thanks for another patch :)

My initial response to this is that this looks fully reasonable. Code-wise, there's some style-issues you'll need to fix (double-quotes, not single), but as far as I can tell, that's about it.

It we're lucky, this may also fix the problems we have with https://github.com/KartikTalwar/gmail.js/issues/379.

Before merging though, we will need to quickly map out how much calling code is impacted, and what kind of testing we will use to ensure that we're not breaking anything.

**Comment by Navega** [comment]
Hey there,

I fixed the code style, thanks!

I just saw that you use the same "dataType" config in the function "make_request_async", so I am very confident with the fix, and our QA department tested it our Gmail Extension and it works fine with the new fix. It isn't critical, the only real problem is a parsing jquery action which is sending error messages to our loggers.

If you need something from me, only tell me.

**Comment by josteink** [comment]
Sounds good. I don't think I'll need much more help on your part.

That said: I'd like to do some basic end-to-end testing on a complex extension I'm responsible for before committing, and I'm not sure when I'll have time to do that. Quite busy at work now...

If you feel things are taking too long time, don't be afraid to remind me :)

**Comment by Navega** [comment]
Ok, thanks @josteink!!

**Comment by josteink** [comment]
I've never had this issue with the (ancient) version of jQuery we've shipped by default, but when testing with a modern version (as in #379), I can reproduce the issue.

Testing my most sophisticated and intricate extension using your patch and latest jQuery, I get no warnings and everything works fine.

Thanks for the patch. Feel free to keep them coming :)

**Pull request merged**
