### PR TITLE
Add thread_id to dom.compose to match email data structure

### PR DESCRIPTION
**Pull request by ek23**

### CODE REVIEW

**Comment by josteink** [comment]
Hey there and thanks for the patch.

This looks promising, and I'll be happy to merge it once done.

However when testing it right now I get some "dirty" results:

````javascript
let c = gmail.dom.composes()[0]
c.thread_id()
// "thread-f:1610056787031797158|msg-f:1610056787031797158"
````

From that function call I would expect to receive `"thread-f:1610056787031797158"` only. Can you look into that?

**Comment by ek23** [comment]
Yes, we would only want the thread section from your output.  It would be easy enough to pull out the thread id, but I am unable to reproduce.  The "rt" input only has the thread id if I am composing or replying.  Is there something I am not thinking of?  I originally copied over the code from email_id just above

**Comment by josteink** [comment]
I just clicked reply to an existing email in an existing thread, and that's what I got. Either way, it should be fairly simple to filter that, and to make a unit-test for it.

>  The "rt" input only has the thread id if I am composing or replying. Is there something I am not thinking of? I originally copied over the code from email_id just above

Maybe I'm just thick, but I couldn't find the relevant code you're referencing. Could you help me out?

**Comment by josteink** [comment]
Any update on this one?

I'm not going to merge this until the function returns a clean thread_id, and I can't really find the other code you referenced, so I'm not sure what other code we may have to look into fixing too.

Care to help me out?

**Comment by josteink** [comment]
Any update on this one yet? @ek23 ?

**Comment by ek23** [comment]
I added the check for the thread|msg format and the TS definition, but I couldn't see where to create the unit test.  Can you point me to where that should go?

The "rt" was referring to the last line in the PR - thread: "input[name=rt]".   I was just looking at the HTML that dom.compose was pulling from.  Sorry for the delay on answering that, I know I had started on a response but must have never pushed the Comment button.

**Comment by josteink** [comment]
Taking a look at the code, that does look fairly simple.

I guess we *could* write tests for it, if we restructured the thread_id() function to obtain data only, and pass the result to another pure filtering helper-function, in the api.helper-namespace.

That way we could write tests for the filtering function directly without needing a DOM or a real message.

If you feel like doing that, that would be great. If not, no big deal. You decide. :smile:

**Comment by ek23** [comment]
What do you think about adding a dev dependency to jsdom so we can test functions that use jquery?  There are a lot of those in api.dom.compose.prototype.  It was pretty easy to fake a compose email with just the input that thread_id() needs.

**Comment by josteink** [comment]
From the build log:

````
npm ERR! Linux 4.15.0-1028-gcp
npm ERR! argv "/home/travis/.nvm/versions/node/v6.17.1/bin/node" "/home/travis/.nvm/versions/node/v6.17.1/bin/npm" "run" "test"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! gmail-js@0.9.6 test: `mocha test/test.*.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gmail-js@0.9.6 test script 'mocha test/test.*.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
````

Node 6 is pretty old. We should probably update our CI to latest.

**Comment by josteink** [comment]
Aaaaand done. CI is on Node 10 now.

Rebase from current master, and your CI should be good.

**Comment by josteink** [comment]
>  what do you think about adding a dev dependency to jsdom so we can test functions that use jquery? There are a lot of those in api.dom.compose.prototype. It was pretty easy to fake a compose email with just the input that thread_id() needs.

*In general:* Mixed feelings. I like unit-tests which are simple and straight to the point. On the hand, having less concise tests which closer mimics what the end-user runs is not a bad thing either.

I also have experience with JSDom being somewhat flaky/unstable when you have several tests running, causing random, impossible-to-debug build failures.

Looking *specifically* at these tests though, I'm OK with that. The setup is still pretty simple, and it's easy to see what is being tested.

If JSDom starts giving us issues, I'll revisit this stance later on, but for now I have no problems.

Just fix your CI, and I'll be glad to merge.

**Comment by josteink** [comment]
Also: The changelog for 0.9.7 is starting to become unusually big: https://github.com/KartikTalwar/gmail.js/blob/master/CHANGELOG.md

I guess when we land this PR, I will add that to the changelog and push 0.9.7 out to npm. No pressure 😄

**Comment by ek23** [comment]
The CI was fine locally.  I even re-cloned and still couldn't reproduce the error.  It looked like an issue with an unrelated npm package.  I reverted the commit that added jsdom and everything passed.

You want to just merge without the tests?  I have never been good at dealing with npm package issues.

**Comment by josteink** [comment]
No no. Please re-add the tests. The problem was that the CI was running on a VM with Node 6, and JSDom required a newer version.

**Comment by josteink** [comment]
No no. Please re-add the tests. The problem was that the CI was running on a VM with Node 6, and JSDom required a newer version.

This is defined in the `.travis.yml` file, and until you rebase your changes on the *current* master-branch, your CI-config will still run with Node 6.

If you don't want to/know how to rebase, just update the Node-value in your .travis.yml to 10 (like in Git master) so that the CI for this PR runs with a modern version.

**Comment by ek23** [comment]
Ok, thanks for the help.  Looks god now.

**Comment by josteink** [comment]
Thanks. Merged! Will release new version to npm next week 🙂

**Pull request merged**
