### PR TITLE
Close compose window

### PR DESCRIPTION
**Pull request by bagbee**
Added a method to close compose window

### CODE REVIEW

**Comment by josteink** [comment]
Hey there and thanks for the PR!

From what I can tell, this attempts to close the compose-window by emulating a user pressing ESC. Are there any known cases where this will fail?

Apart from that: The overall code looks fairly clean, and I appreciate that you've updated the TypeScript bindings. Would you be able to update the Compose-documentation in README.md too?

**Comment by bagbee** [comment]
Hey

All works fine for me, without fail cases.

As for the documentation in README.md, I do not see a section for the Compose object.

**Comment by josteink** [comment]
Well there *is* a section but it’s absolutely lacking in coverage, I’ll give you that:

https://github.com/KartikTalwar/gmail.js/blob/master/README.md#gmaildomcomposecompose_el

If you can help start improving it, maybe I’ll get around to completing it later? 🙂👍

**Comment by bagbee** [comment]
Done :slightly_smiling_face: 

Please check.

**Comment by josteink** [comment]
Wow. That's absolutely fabulous! You more or less *completed* that section.

Good job! Consider it merged!

**Pull request merged**
