### PR TITLE
use MutationObserver to track dom node additions.

### PR DESCRIPTION
**Pull request by cancan101**
Closes https://github.com/KartikTalwar/gmail.js/issues/766

CC @Kravimir @josteink

### CODE REVIEW

**Comment by josteink** [comment]
Hey @cancan101 and thanks for the super-quick pick!

The change looks simple enough. I've also tested with my own extension, everything works, and from what I can tell there are no adverse effects.

I'd be happy to merge this change. How about about you @Kravimir?

**Comment by josteink** [comment]
No feedback from @Kravimir in roughly a week... So I say this is good to merge.

**Comment by Kravimir** [comment]
Not necessarily. In my case it often means I haven't remembered to come back to look at it.

However, in this case, the change is good, although I do note that the observed node is changed from "document" to "document.body".

**Review by josteink — APPROVED** [review]

**Comment by josteink** [comment]
> Not necessarily. In my case it often means I haven't remembered to come back to look at it.

I know such things happen. It happens to me too!

But that often mean an issue isn't *that* critical to the person involved. In those cases, if others feel a need to move on, it should be OK to do so, especially if notifying about that happening 😄 

> However, in this case, the change is good, although I do note that the observed node is changed from "document" to "document.body".

Nice observation. Looking into docs here, I don't think this is going to be an issue for our use.

We're never going to need to inspect for changes in the `<HEAD>` element are we?

**Comment by cancan101** [comment]
so, can this PR be merged?

**Comment by josteink** [comment]
Yeah. Sure thing. Sorry about the delay!

**Comment by cancan101** [comment]
Can we can a release cut with this PR? I think `gmail.observe.on('view_thread')...` may be broken without it. See: https://github.com/KartikTalwar/gmail.js/issues/765

**Pull request merged**
