### PR TITLE
fix #368 - avoid accessing window.opener from another origin

### LINKED ISSUE #368: window.opener explodes
```
      typeof(window) !== "undefined" && window.opener !== null && typeof window.opener.GLOBALS !== "undefined"
          ? window.opener.GLOBALS
```

This code blows up if you open gmail from a link on another domain with a cross-origin request denied error.

### PR DESCRIPTION
**Pull request by onestep**

### CODE REVIEW

**Comment by onestep** [comment]
I've updated original fix to access `document.domain` instead of `document.location`, not a really necessary change, but accessing string property looks cleaner for me.

**Comment by josteink** [comment]
For some reason I never saw this PR and I'm really sorry about that.

However, it seems like the issue you wanted to address was just fixed by another, merged PR: https://github.com/KartikTalwar/gmail.js/pull/559

Is the merged fix sufficient for you, or are there more things you think we should address?

**Comment by onestep** [comment]
This pull request actually fixes other thing, described in #368 (we had a conversation there).

Currently it has conflicts and should be updated to match new changes. Please let me know if it's needed, otherwise I can just close it.

**Comment by josteink** [comment]
Just checked that other conversation, and if this is about third party origins, I do agree we should merge this too.

If you can resolve the conflicts, and provide a clean PR for this, I'll be happy to merge, and without months of waiting this time around :)

**Comment by onestep** [comment]
Thank you, I've updated code to match current master. Please review and let me know if you have any questions.

**Comment by josteink** [comment]
Thanks. That looks good!

I’ll try to get this tested tomorrow, and if nothing seems broken, you can consider it merged!

**Comment by josteink** [comment]
Merged and published in v0.9.7.

**Pull request merged**
