### PR TITLE
GLOBALS and VIEW_DATA undefined error fix

### PR DESCRIPTION
**Pull request by itsazzad**

### CODE REVIEW

**Comment by KartikTalwar** [comment]
@itsazzad before I merge this, can you tell me when you are seeing the undefined error? When does it happen, what pages does it happen on? I'd like to reproduce it

**Comment by itsazzad** [comment]
It happened on GMail page load.
screen shot 2016-01-05 at 11 21 03 pm

**Comment by KartikTalwar** [comment]
Would it be possible to see how the chrome extension is being loaded? To me this sounds like `Gmail()` functions are being called before the page is completely loaded..

**Comment by itsazzad** [comment]
I started with https://github.com/KartikTalwar/gmail-chrome-extension-boilerplate

**Comment by itsazzad** [comment]
So https://github.com/KartikTalwar/gmail-chrome-extension-boilerplate/blob/master/main.js is making it

**Comment by itsazzad** [comment]
I have found the issue.
If the extension is not restricted to GMail only then the errors coming.
So my suggested fork is suitable if in need of message passing with another domain.

**Comment by KartikTalwar** [comment]
Thanks for giving those details. Since it is not recommended to run/include the js file for other domains in your manifest, for now I will close this pull request.

**Pull request closed without merging**
