### PR TITLE
replacing query param "mbox" (for enterprise gmail account, apparently) with "inbox"

### PR DESCRIPTION
**Pull request by Banjerr**
I ran into an issue described [here](https://github.com/KartikTalwar/gmail.js/issues/247), where `visible_emails `would only pull back 45 results; switching `mbox` with `inbox` fixed the issue.

### CODE REVIEW

**Comment by KartikTalwar** [comment]
Hey @Banjerr thanks for the PR! The comment in #247 says:

> for enterprise gmail inbox, it should be `"inbox"`.

Is the query param only a problem for google apps accounts or is it also a problem for gmail.com accounts?

**Comment by Banjerr** [comment]
Hi @KartikTalwar 

Good question. I was testing this on my work account, which I believe is a google apps account, but just tested on my personal account (which I *believe* is a gmail account) and it had the same behavior. So, I'm not entirely sure, but I believe it's an issue for both

**Comment by KartikTalwar** [comment]
I tested it locally and seems to work for me. In case anyone else has issues, please bring it up as a new issue - merging for now

**Comment by josteink** [comment]
Good approach. No need to leave PRs hanging needlessly :)

**Pull request merged**
