### PR TITLE
I want to be able to get the trimmed part of the body when editing - …

### PR DESCRIPTION
**Pull request by ibercovich**
…using compose.dom('trimmed').val()

If there is a better way, please let me know.

### CODE REVIEW

**Comment by josteink** [comment]
I don't see the use for this myself, but I don't see any reason not to add it either.

That said, if you are adding new methods, please also add them to the documentation in `README.md`.

**Comment by josteink** [comment]
Forgot one final part: It also needs to be added to the typescript type-annotations in gmail.d.ts:

https://github.com/KartikTalwar/gmail.js/blob/4f0b48309fa0d8f3c1fee3d3fffa7bd89df877f0/src/gmail.d.ts#L486-L488

And a final question (because I'm obviously going to test this before I merge), what is the expected behaviour of this selector? What part of the compose dialogue is it supposed to extract?

Currently, with this email:
image

I'm getting these results:
image

Is that the expected value?

**Comment by ibercovich** [comment]
Hopefully this screenshot helps clarifying. There might be a better way to accomplish the same thing with existing functionality.

image

**Comment by josteink** [comment]
Yeah that seems to work. Thanks for clearing it up.

Before putting any more work into this, I was wondering if perhaps we could come up with a better name. In my opinion `trimmed`  is not very descriptive, and I certainly didn't understand what to look for.

What about `quoted_reply` instead?

If that's OK, feel free to update the code, the readme and the typescript definitions, and I think we can call it a day :smile:

**Review by josteink — APPROVED** [review]

**Comment by josteink** [comment]
Thanks. Merged!

**Comment by cancan101** [comment]
Is there anyway to modify the `quoted_reply` in a way that is respected when the compose is sent?

Ie it looks like calling:
```ts
compose.dom('quoted_reply').val('FOOOO')
```
Does not in fact change the contents of the sent email message.

**Pull request merged**
