### PR TITLE
add read/unread actions

### PR DESCRIPTION
**Pull request by hankypanky666**
add read/unread actions for new gmail ui and dataLayer

example: 
```
gmail.observe.before(
                'unread',
                (oldIds, paramsUrl, paramsBody, newEmailIds, newThreadIds) => {
                    startForcedSync();
                }
            );
```

### CODE REVIEW

**Comment by josteink** [comment]
Wow. *That* is all the changes which is needed?

Nice! Guess that means we did some solid work on the first PR :)

I’ll have to test this before merging, but if it works I have no further objections.

**Comment by josteink** [comment]
I just tested this, and as far as I can see, the `unread` event works fine. However the `read` event doesn't trigger at all, at least not from the Inbox.

I've used the following code for verification:

````javascript
gmail.observe.before(
                'unread',
                (...args) => {
                    console.log("UNREAD!!!", args);
                }
            );
gmail.observe.before(
                'read',
                (...args) => {
                    console.log("READ!!!", args);
                }
            );
````

Have you tested the `read`-event yourself? How did you make it work?

I'm getting some weird `read`-event notifications when navigating to a an already read email from the inbox, and I get them every time.

I'll have to consider that test failed for now.

That means we have at least 2 options:

* fix the `read`-event to trigger when expected, and just as importantly, NOT trigger for unrelated events.
* remove the support for the `read`-event, only merging support for `unread` for now.

What do you think?

**Comment by josteink** [comment]
OK. I can verify that these events works as advertised.

If we merge this, we will then also fix https://github.com/KartikTalwar/gmail.js/issues/484 in the process :)

I'm OK with merging this now, as is. Is that OK with you too, or are there other changes you would like to make first?

**Comment by hankypanky666** [comment]
ok, merging) as there will be time, I will try to make cheker for 'read' action, thanks!

**Pull request merged**
