### PR TITLE
Add CDNJS and npm version badges in README.md

### PR DESCRIPTION
**Pull request by sufuf3**
These badges will show the version on CDNJS and npm.

### CODE REVIEW

**Comment by josteink** [comment]
Hi there and thanks for the patch!

While I’m fine with having badges in general, I have 2 questions:

* is shields.io an officially sanctioned way to get a NPMJS badge? (Similarly for CDNJS)
* should we encourage use of CDNs for libraries used inside browser extensions? I think that sounds very strange and I think we may be better off without it. 

Any opinions, @KartikTalwar ?

**Comment by KartikTalwar** [comment]
Having the latest version on npm definitely makes sense but I agree, it might be confusing for others to see gmail.js on cdnjs and wonder how to use it since it only works for chrome extensions. I don't have any strong objections to it, but do believe that it'll lead to confusion

**Comment by sufuf3** [comment]
@josteink @KartikTalwar Thank you for your suggestion.
IMO, the front-end developers know how to use web public CDN and add this badge will help them know more information.
So I think maybe it's good to have.

But if you think it's not necessary I'll update this PR, let it better to merge.
What do you think?

Thank you very much.

**Comment by josteink** [comment]
I guess that settles it: NPM badge is fine. CDNJS might confuse people.

**Comment by sufuf3** [comment]
Removed the CDNJS badge part
Please help me review this PR, Thanks. :)

**Comment by josteink** [comment]
Unless @KartikTalwar has any objections, I'll be absolutely happy to merge this.

It looks nice :)

**Comment by KartikTalwar** [comment]
👍

**Comment by josteink** [comment]
Thanks for the patch. Merged!

Feel free to submit more in the future!

**Comment by sufuf3** [comment]
Thank you! :)

**Pull request merged**
