### PR TITLE
Updated make_request function to get raw massage from the new show_original page format of Gmail

### PR DESCRIPTION
**Pull request by bravin8**
Gmail.js API using tools.make_request function to visit the show_original page to get the email source. Since Gmail changed that page format from raw message to different html format i made some changes in the make request function to get only the raw massage.

### CODE REVIEW

**Comment by josteink** [comment]
Speaking as a fellow gmail.js user, the new format returned is indeed less useful. The RAW mime message is still there, but like you've noticed burried inside a element with id "raw_message_text".

Getting the MIME message out means re-making DOM elements, and doing lots of wasteful/inefficient operations. I'm very much for a PR like this, epsecially since it means making the api.get.email_source()-function do what it actually says in the documentation.

My only concern would be making sure this is done in way compatible across Gmail versions (since Google apps-users may be stuck on older versions for quite a bit). Is there any reliable way to do that?

@KartikTalwar: Speaking as a contributor with push-access... Would it be OK for me to approve and merge PRs like this in the future, once obvious issues like conflicts has been resolved?

**Comment by KartikTalwar** [comment]
Sorry for the late replies to this pr but I agree with @josteink's comments. Compatibility becomes an issue, although I think the new message format is consistent on personal and gapps accounts. That being said, @josteink please feel free to merge any PRs that you think are good!

**Comment by josteink** [comment]
Here's my proposal:

1. Wrap the Domparser logic in a try-catch.
2. Check if you can find the named element.
3. If any error happens, or the element can not be found... Then assume response-text is the RAW mime-message and that any further processing is unneeded.
4. Otherwise return contents of element, as your code already does.

I think that should address all compatibility-concerns, and I'd be happy to merge that.

**Comment by josteink** [comment]
I'm eager to get old PR's closed, so I took some liberties:

* I took the existing implementation, and made the changes I suggested.
* I moved the *location* of the code to email_source (where it logically belongs) instead of in make_request.

With that, `api.get.email_source()` should now always return MIME-messages, as the documentation says it does.

Thanks for the patch!

**Comment by bravin8** [comment]
@josteink Great work mate.

**Pull request merged**
