### PR TITLE
Fixed compose buttons being duplicated when using add_compose_button multiple times

### PR DESCRIPTION
**Pull request by DrParanoia**
I you try to add two buttons using `add_compose_button` you will get three, if you try to add three buttons, you will get 6 and so on...

### CODE REVIEW

**Comment by josteink** [comment]
Hey there and thanks for the PR. 

The change looks reasonable to. Thanks for the fix!

Could also bump the version and add your fix to the change log?

**Comment by DrParanoia** [comment]
@josteink Sure, just a sec

**Comment by DrParanoia** [comment]
@josteink Done! 😄

**Comment by josteink** [comment]
Thanks. Great! Consider it merged!

I'll try to get a new version out to npm js later today 🙂

**Comment by DrParanoia** [comment]
@josteink Thanks a bunch!

**Comment by josteink** [comment]
Now published on npmjs as 1.0.19!

https://www.npmjs.com/package/gmail-js

**Pull request merged**
