### PR TITLE
Gmail updated DOM location of email id

### LINKED ISSUE #255: Cannot read property 'pop' of null
I got this error:
gmail.js:2342 Uncaught TypeError: Cannot read property 'pop' of null

I write this quick fix:
```js
if(this.id_element.attr('class').match(/(^|\s)m([\S]*)/) != null)
        this.id = this.id_element.attr('class').match(/(^|\s)m([\S]*)/).pop();
```

### PR DESCRIPTION
**Pull request by brentkelly**
Fix to find id of an email in the DOM tree after gmail updates.

Fixes #255

### CODE REVIEW

**Comment by nathan-muir** [comment]
I noticed a few other breakages when patching this one.

Fixes can be found here: https://github.com/nathan-muir/gmail.js/commit/405682538b0d2a6bd5db297578e1e2abf2b0f7be

**Comment by YesThatAllen** [comment]
I applied these to lines 2332 and 2341 in master today, and it fixes https://github.com/KartikTalwar/gmail.js/issues/275

**Comment by steelx** [comment]
Im still not able to catch any events on Observe method.

**Comment by josteink** [comment]
Can you confirm if this works without these changes?

Maybe we need to look in both locations?

**Pull request merged**
