### PR TITLE
fix gmail.dom**.right_toolbar()**

### PR DESCRIPTION
**Pull request by stevepeak**
Screenshot 2023-02-10 at 11 54 24 AM

`$("[gh='tm'] [gh='s']")` does not appear to exist any more.

### CODE REVIEW

**Comment by josteink** [comment]
Hey there and thanks for the patch.

I've tested it, and from what I can tell, it works correctly.

Before merging though, I would please ask you to do 3 things:

* update the version in package.json
* update the changelog
* fix the in your patch. you are currently using tabs, but the rest of the file uses spaces

If you can do that, I'll be sure to get this merged and released as a new verison on npmjs!

**Comment by josteink** [comment]
Any news on this one? :)

**Comment by stevepeak** [comment]
@josteink I do plan to hack on this, I've just been very busy. I appreciate your patience.

**Comment by josteink** [comment]
LGTM. Consider it merged!

**Comment by josteink** [comment]
Now live in 1.1.10 on npmjs.

**Pull request merged**
