### PR TITLE
Add Start Reply

### PR DESCRIPTION
**Pull request by kstubs**
Support for clicking Reply button in email

### CODE REVIEW

**Comment by josteink** [comment]
Hey there and thanks for the patch!

Looking at the code itself, apart from using plain DOM-objects, it looks mostly like the `send()` implementation we have on `api.dom.compose`-instances: https://github.com/KartikTalwar/gmail.js/blob/50291f74cf2ed8dff243c573eec1b1710cd6ec8c/src/gmail.js#L3480-L3485

One key difference which I see though is that this seems to be implemented globally. Was that intentional?

Is that going to be a source of errors/limitations? Could there be cases where we would rather want to reply to a specific `api.dom.email`-instance? It also seems to reply to the *first* email it finds with a reply-button (as opposed to the last), and I don't think that is what people are going to expect.

It might make more sense to add this method to the `api.dom.email`-object, and maybe even return the resulting `api.dom.compose` once invoked?

What do you think?

Apart from that, once we settle *where* this could should be and how it should work, we will probably also want this added to the documentation and typescript type-annotations. For now though, that should probably wait.

**Comment by josteink** [comment]
Hey @kstubs.

Did you read my reply? Do you have any opinion on it?

I'm not going to merge this as is, so if you want this added, you will need to provide me with some feedback :)

**Comment by kstubs** [comment]
Hi Jostein,
Sorry for the late reply but I've just been pulled away to some other
things in last 1-2 months.  I'm not abandoning this pull-request, but just
not able to get back to it with proper and necessary time to make the
changes (which I really appreciate, your excellent feedback on this).
So, not dropped, not forgotten, but can we leave it as is for now?

Karl Stubsjoen
(602) 845-0006

**Comment by josteink** [comment]
Fair enough. Just checking in :+1:

**Comment by kstubs** [comment]
Getting back into this Jostein but having issues.  I researched this issue
#558
... and left my comments there.  Basically, email_data() returning Null.

Thanks!

Karl Stubsjoen
(602) 845-0006

**Comment by kstubs** [comment]
Wow!  Just looking at recent issues in Github and see # 589 "cache missing
first couple messages" and realize this is exactly the bug I am
experiencing.  I can work around this for now!

Karl Stubsjoen
(602) 845-0006

**Comment by josteink** [comment]
Agreed about #589. My plan is to get a PR supposedly fixing that merged as quickly as possible.
So let's just assume that's not a problem, and move on to *your* PR!

Looking at the current state of the code, I can't see any updates based on [my review so far](https://github.com/KartikTalwar/gmail.js/pull/587#issuecomment-524730256)... Or am I mistaken?

I'd really like for those things to get better fleshed out, or at least discussed before considering merging this. A public API is something one should be careful about introducing after all :smile:

**Comment by josteink** [comment]
@kstubs Your issue should now be fixed in a new and shiny `1.0.0` release. Please read the changelog :)

**Comment by josteink** [comment]
This PR hasn't been active or touched in *years*. Closing. Let me know if you're still interested in getting this merged.

**Pull request closed without merging**
