### PR TITLE
Fix incorrect variable name in GmailCache definition

### PR DESCRIPTION
**Pull request by ajmssc**
The threadCache variable name is incorrectly defined in the d.ts file

### CODE REVIEW

**Comment by josteink** [comment]
Right you are!

Could you update the change log and bump the version?

After that we can get this merged and push a new version to NPMJS.

**Review by josteink — APPROVED** [review]

**Comment by ajmssc** [comment]
done

**Review by josteink — APPROVED** [review]
LGTM!

**Comment by josteink** [comment]
Merged. Thanks for the contribution! Now published on npmjs!

**Pull request merged**
